### ISSUE TITLE
Read & Search Geoid Data

### ISSUE THREAD

**Issue by BatchelorJ** [GeoscienceAustralia/GeodePy#16]
Currently geoid data is stored in ASCII .dat and NTv2 .gsb formats. This module requires a way to read this data into a Python data structure (e.g. a NumPy array or PyTable object?) and search through to find specific latitude and longitude values.

![capture2](https://user-images.githubusercontent.com/35472516/36364451-5a0f7cf0-1598-11e8-9e50-4060b55e2923.PNG)

**Comment by JaimieDodd** [comment]
Hi,

I have written a python script which can read the NTv2.gsb file.

The script contains a couple of classes with multiple functions, but you only need to call NTv2ReaderBinary().ntv2reader(file, lat, lon, interpolation_method), where:
•	file is the complete file location as a string
•	lat is the latitude of the point of interest in decimal degrees
•	lon is the longitude of the point of interest in decimal degrees
•	interpolation_method is either ‘bilinear’ or ‘bicubic’ (by default I have set it to ‘bicubic’, so this parameter isn’t mandatory).

The other class and functions are called within that one. 

The output is a tuple of the ellipsoid to AHD separation, deflection in the prime meridian and deflection in the prime vertical values in that order (NAHD, ξ, η).

Output values have been checked against results using DynaNet and this online calculator (http://www.ga.gov.au/ausgeoid/).

If you are interested, I am happy for this script to be a part of the GeodePy package. 

- Jaimie Dodd, Geodesy and Positioning Unit, Queensland Department of Natural Resources, Mines and Energy

**Comment by JaimieDodd** [comment]
Hi Josh,

Awesome! I think I may need to be given permission to push to this repository, as I just got the following error:

> git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin feature/ntv2_reader:feature/ntv2_reader
> remote: Permission to GeoscienceAustralia/GeodePy.git denied to JaimieDodd.
> fatal: unable to access 'https://github.com/GeoscienceAustralia/GeodePy.git/': The requested URL returned error: 403
> 
> Pushing to https://github.com/GeoscienceAustralia/GeodePy.git
> Completed with errors, see above.

**Comment by harry093** [comment]
Hi Jaimie,

You will need to do this through a pull request. If you fork the GeodePy repository and add the code to your version (by committing and pushing the new code to your fork) you can then issue a pull request to the main repository that we can then review and merge.

Cheers, Craig

**Comment by BatchelorJ** [comment]
Thanks very much Jaimie, we'll review it and get back to you with any feedback we have.

Cheers,
Josh

**Comment by harry093** [comment]
Features added in #51
