### ISSUE TITLE
Survey Conversion: Liscad Field File to GeodesyML

### ISSUE THREAD

**Issue by BatchelorJ** [GeoscienceAustralia/GeodePy#19]
- [ ] lisfield2geodesyml
Tool to convert Liscad Field file to GeodesyML format ready for import and processing in DynaNet.

**Comment by harry093** [comment]
@BatchelorJ has this functionality been moved to PynAdjust?

**Comment by harry093** [comment]
@BatchelorJ has this functionality been moved to PynAdjust?

**Comment by BatchelorJ** [comment]
This functionality is better placed in https://github.com/icsm-au/PynAdjust. A new issue has been raised for this functionality there.
