### ISSUE TITLE
MGA94 <-> MGA2020

### ISSUE THREAD

**Issue by harry093** [GeoscienceAustralia/GeodePy#71]
It would be good to create a function that strings together all the other necessary functions to do this. Emails to geodesy@ga are making it obvious that people think this is a simple transformation. Required steps:

MGA94<->GDA94 lat/lon<->GDA94 XYZ<->GDA2020 XYZ<->GDA2020 lat/lon<->MGA2020

**Comment by BatchelorJ** [comment]
Functionality added in #72, closing
