### ISSUE TITLE
Provide test coverage for the statistics module

### ISSUE THREAD

**Issue by harry093** [GeoscienceAustralia/GeodePy#82]
- [ ] rotation_matrix()
- [ ] vcv_cart2local()
- [ ] vcv_local2cart2()
- [ ] error_ellipse()
- [ ] circ_hz_pu()
- [ ] k_val95()

**Comment by Physsix27** [comment]
I would like to work on this issue. So I can understand a little what you want, Do you want uni test for those specific function for the `statistic.py` python file.
Can you assign this issue to me, I will work on it?

**Comment by BatchelorJ** [comment]
Hi @Physsix27, that would be great! Yes we're looking for test coverage for each of these functions added as a new `test_statistics.py` module in geodepy.tests.

The Dynanet/DynAdjust documentation mentioned in the function docstrings can be found at the following [link](https://github.com/icsm-au/DynAdjust/blob/master/resources/DynAdjust%20Users%20Guide.pdf).

**Comment by Physsix27** [comment]
Can you check my PR, I am done #84

**Comment by Physsix27** [comment]
Can you review/merged #84  @harry093 @BatchelorJ
